### PR TITLE
spinner/Loader

### LINKED ISSUE #28: Add spinner/loader component

### PR DESCRIPTION
**Pull request by flow6979**

### CODE REVIEW

**Comment by flow6979** [comment]
you can review my PR @imabhinavagarwal and tell if you need some changes or you are good to go for merger

**Review by imabhinavagarwal — CHANGES_REQUESTED** [review]
Your code has blocked the loading of components page entirely. 
Also, please do not use gif for spinner

**Comment by flow6979** [comment]
wait i have done if for all instead of a component
wait let me change

**Comment by flow6979** [comment]
> Your code has blocked the loading of components page entirely. Also, please do not use gif for spinner

firstly tell me that if you want it as component or fall all page?

**Comment by imabhinavagarwal** [comment]
> firstly tell me that if you want it as component or fall all page?

As a component

**Comment by flow6979** [comment]
> Your code has blocked the loading of components page entirely. Also, please do not use gif for spinner

what do you want instead of gif brother?

**Comment by imabhinavagarwal** [comment]
> what do you want instead of gif brother?

We can make it using css alone.. no need of external image or gif

**Comment by flow6979** [comment]
> > what do you want instead of gif brother?
> 
> We can make it using css alone.. no need of external image or gif

ok brother

**Comment by flow6979** [comment]
can you please check it now?

**Comment by flow6979** [comment]
if correct please merge it or tell me the things to change. i have a class right now, if changes are needed i will do it by night

**Review by imabhinavagarwal — APPROVED** [review]
Just a tip, in css class names, id names, etc start from lowercase

**Comment by flow6979** [comment]
> Just a tip, in css class names, id names, etc start from lowercase

yus sirrrrrrrr, thanks for the tip

**Pull request merged**
